### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by gleporeNARA** [perrinjerome/mitene_download#2]
Suggestion for additional features, might need to move each suggestion to its own issue.

Support renaming downloaded files to remove extra characters

Support for parallel downloading

Support incremental updates or refreshing of downloads so as not to download photos which have already been downloaded

Download highest quality images
Currently the program downloads the lower quality image presented on the initial page. The higher quality images are available by clicking on each image and selecting "Save".  For example, for one image, the lower quality file is 1440x1920, while the higher quality image is 3024x4032.

**Comment by perrinjerome** [comment]
Thanks for the suggestions !

> Download highest quality images

That's really a good point, I totally missed this. I implemented this in 59e1b9a77cd8e4b92a0ed41e19910b6dfe4efb64

> Support for parallel downloading

I was not sure this would actually be faster, but I gave it a try. I switched to aiohttp / asyncio. It's super easy to achieve parallel downloads with a semaphore.

From my home connection with a 884M, I measured these timings:
 * previous version with requests: 71,01 secs
 * switching to aiohttp, but running sequentially:  70,66 secs 
 * aiohttp 4 coroutines:  30,58 secs 

so it's more than twice faster, thanks also for this idea !

> Support incremental updates or refreshing of downloads so as not to download photos which have already been downloaded

Actually it already work like this. If a media is already downloaded it's not downloaded again. This relies on the filenames, so it works because they use uuid.

> Support renaming downloaded files to remove extra characters

This could be nice, but it would be harder to implement the previous item (incremental updates), maybe we would need a database of already downloaded or something. For now I don't see how to do it and to be honest I don't think I will implement because I don't think I need it. 

PS: I published a version 0.1.0 on pypi with these changes, thanks again !

**Comment by gleporeNARA** [comment]
Looks great! I downloaded 16GB in 30 minutes on a 300MB connection, over 4,300 files. 

I understand the renaming issue would be tricky, plus it would break the refresh feature, so no worries about that. I can always rename them later.

Thanks for working on this and responding to my issues, right now the code does everything I want!

**Comment by perrinjerome** [comment]
Great to read that it works for you. Thanks again for the suggestions here !
